
import Foundation

struct placesStruct {
    var name: String
    var textAbout: String
    var photo: String
    var latitude: String
    var longitude: String
    init(name: String, textAbout: String, photo: String, latitude: String, longitude: String ) {
        self.name = name
        self.photo = photo
        self.latitude = latitude
        self.longitude = longitude
        self.textAbout = textAbout
    }
}


var arrayPlaces = [
    placesStruct(name: "Eastern State Penitentiary", textAbout: "  Eastern State Penitentiary Historic Site was once the most famous and expensive prison in the world, but stands today in ruin, a haunting world of crumbling cellblocks and empty guard towers. Known for its grand architecture and strict discipline, this was the world’s first true “penitentiary,” a prison designed to inspire penitence, or true regret, in the hearts of convicts. Tours today include the cellblocks, solitary punishment cells, Al Capone’s Cell, and Death Row.    ",  photo: "Eastern State Penitentiary", latitude: "39.968139", longitude: "-75.171491"),
    placesStruct(name: "Philadelphia Museum of Art", textAbout: "  A surprise around every corner discover the cultural heart of Philadelphia. The Museum’s landmark building houses one of the most remarkable collections in the country, featuring some of the greatest works of American, Asia, and European art anywhere. You’ll find van Gogh's Sunflowers, the world’s largest Marcel Duchamp and the only dedicated Rodin Museum outside France. Eat. Drink. Shop. Whether you’re visiting for the first time or the fiftieth, you’ll always see something new. Catch a world-class exhibition or get to know the masterpieces that live year-round in the Museum’s 200+ galleries, including many stunning architectural spaces and period rooms. ",  photo: "Philadelphia Museum of Art", latitude: "39.965418", longitude: "-75.180709"),
    placesStruct(name: "The Barnes Foundation", textAbout: "  The Barnes Foundation houses one of the finest collections of nineteenth- and twentieth-century French painting in the world. An extraordinary number of masterpieces by Renoir, Cezanne and Matisse provide a depth of work by these artists that is unavailable elsewhere. Established as an educational institution, the Barnes carries out its mission teaching classes in its galleries and Arboretum.",  photo: "The Barnes Foundation", latitude: "39.960390", longitude: "-75.173233"),
    placesStruct(name: "Reading Terminal Market", textAbout: "  Reading Terminal Market is an enclosed public market located at 12th and Arch Streets in Center City Philadelphia, Pennsylvania. It opened originally in 1893 under the elevated train shed of the Reading Railroad Company after the city of Philadelphia advocated to move public markets from the streets into indoor facilities for both safety and sanitary reasons. The Reading Railroad Company owned and operated the market space until 1976 when the company liquidated, leaving the market without its parent company and foot traffic from the train. Presently, it still occupies the ground floor and basement levels of the Reading Terminal's former train shed which is now part of the Philadelphia Convention Center. ",  photo: "Reading Terminal Market", latitude: "39.953200", longitude: "-75.159532"),
    placesStruct(name: "Independence Hall", textAbout: "  Independence Hall is the building where both the United States Declaration of Independence and the United States Constitution were debated and adopted. It is now the centerpiece of the Independence National Historical Park in Philadelphia, Pennsylvania.The building was completed in 1753 as the Pennsylvania State House, and served as the capitol for the Province and Commonwealth of Pennsylvania until the state capital moved to Lancaster in 1799. It became the principal meeting place of the Second Continental Congress from 1775 to 1783 and was the site of the Constitutional Convention in the summer of 1787.A convention held in Independence Hall in 1915, presided over by former US president William Howard Taft.",  photo: "Independence Hall", latitude: "39.949026", longitude: "-75.149817"),
    placesStruct(name: "Museum of the American Revolution", textAbout: "  Experience the Revolution. Join the angry mob that pulls down a statue of King George III. Face the enemy on the front lines of battle while risking everything for the uncertain hope of freedom. Take an engrossing chronological journey that gives you a feel for the Revolution through immersive galleries, digital interactives, recreated historical environments and more.    ",  photo: "Museum of the American Revolution", latitude: "39.948446", longitude: "-75.145421"),
    placesStruct(name: "The Franklin Institute", textAbout: "  Founded in honor of America’s first scientist, Benjamin Franklin, The Franklin Institute is one of America’s oldest and premier centers of science education. The museum is known for blockbuster exhibits, a bevy of interactive ongoing exhibitions, and one-of-a-kind theatrical experiences. Today, the Institute continues its dedication to public education and creating a passion for science by offering new and exciting access to science and technology in ways that would dazzle and delight its namesake. Discover something new at The Franklin Institute, where kids and parents can explore the fun side of science through twelve cutting-edge, hands-on exhibitions. Every day The Franklin Institute provides resources that help people to connect with science and technology in creative ways.",  photo: "The Franklin Institute", latitude: "39.958195", longitude: "-75.173802"),
    placesStruct(name: "One Liberty Observation Deck", textAbout: "  Visitors to One Liberty Observation Deck get a breathtaking look at the historic Philadelphia skyline from a one-of-a-kind vantage point. See the whole city from above and learn about Philly's rich history and culture with interactive touchscreens and free tours Friday-Sunday. One Liberty is one of the best places to take photos in the city and a great place to start your Philadelphia journey.",  photo: "One Liberty Observation Deck", latitude: "39.952587", longitude: "-75.168456"),
    placesStruct(name: "Liberty Bell Center", textAbout: "  The Liberty Bell is an iconic symbol of American independence, located in Philadelphia, Pennsylvania. Once placed in the steeple of the Pennsylvania State House (now renamed Independence Hall), the bell today is located in the Liberty Bell Center in Independence National Historical Park. The bell was commissioned in 1752 by the Pennsylvania Provincial Assembly from the London firm of Lester and Pack (known subsequently as the Whitechapel Bell Foundry), and was cast with the lettering 'Proclaim LIBERTY Throughout all the Land unto all the Inhabitants Thereof', a Biblical reference from the Book of Leviticus (25:10). The bell first cracked when rung after its arrival in Philadelphia, and was twice recast by local workmen John Pass and John Stow, whose last names appear on the bell.",  photo: "Liberty Bell Center", latitude: "39.949922", longitude: "-75.150437"),
    placesStruct(name: "Please Touch Museum", textAbout: "  The Please Touch Museum is a children's museum located in the Centennial District of Philadelphia, Pennsylvania, USA. The museum focuses on teaching children through interactive exhibits and special events, mostly aimed at children seven years old and younger.The museum originally opened at the Academy of Natural Sciences on October 2, 1976, in a 2,200-square-foot (200 m2) space, and moved to another location on nearby Cherry Street two years later. In 1983, the museum moved to 21st Street near the Franklin Institute. On February 14, 2005, the museum received an 80-year lease for Memorial Hall (in Fairmount Park), the last major building left from the 1876 Centennial Exposition. This came after plans to relocate the museum to a location at Penn's Landing fell through.",  photo: "Please Touch Museum", latitude: "39.979023", longitude: "-75.209478"),
    placesStruct(name: "Rodin Museum", textAbout: "  With over 140 bronzes, marbles, and plasters - including 'The Thinker' - the distinguished collection housed in the Rodin Museum represents every phase of Auguste Rodin’s career. Located on Philadelphia’s Benjamin Franklin Parkway, the elegant Beaux-Arts–style building and garden offer an absorbing experience and the largest collection of Rodin's work outside of Paris.",  photo: "Rodin Museum", latitude: "39.962001", longitude: "-75.173659"),
    placesStruct(name: "Citizens Bank Park", textAbout: "  Citizens Bank Park is a baseball stadium located in Philadelphia, Pennsylvania, within the city's South Philadelphia Sports Complex. It is the home of the Philadelphia Phillies, the city's Major League Baseball (MLB) franchise. It opened April 3, 2004, and hosted its first regular-season baseball game on April 12 of the same year, with the Phillies losing to the Cincinnati Reds, 4–1.The ballpark was built to replace the 33-year-old, now-demolished Veterans Stadium, (a football/baseball multipurpose facility), and features a natural grass-and-dirt playing field and a number of Philadelphia-style food stands that serve cheesesteak sandwiches, hoagies, Tastykakes, soft pretzels, Schmidt and Yuengling beer, and many other regional specialties.",  photo: "Citizens Bank Park", latitude: "39.904584", longitude: "-75.166270"),
    placesStruct(name: "Rocky Statue", textAbout: "  The 72 stone steps before the entrance of the Philadelphia Museum of Art, in Philadelphia, Pennsylvania, have become known as the 'Rocky Steps' as a result of the scene from the film Rocky. Tourists often mimic Rocky's famous climb, a metaphor for an underdog or an everyman rising to a challenge. A bronze Rocky statue was briefly situated at the top of the steps for the filming of Rocky III. This statue, now located at the bottom right of the steps, is a popular photo opportunity for visitors. The top of the steps offers a commanding view of Eakins Oval, the Benjamin Franklin Parkway, and Philadelphia City Hall.",  photo: "Rocky Statue", latitude: "39.965107", longitude: "-75.179663"),
    placesStruct(name: "Philadelphia Zoo", textAbout: "  Animals are on the move like never before at Philadelphia Zoo with Zoo360, a first-in-the-world system of trails passing through treetops, crossing over pathways & connecting habitats, giving animals like amazing big cats, majestic primates & marvelous meerkats the opportunities to travel & explore. Visit our baby western lowland gorillas, giraffes, hippos, polar bear, white rhino, zebras, red pandas, Amur tigers & more at America’s first Zoo. Explore a 42 acre Victorian garden & enjoy award-winning exhibits like KeyBank Big Cat Falls, PECO Primate Reserve, McNeil Avian Center & KidZooU, a wildlife academy that offers dynamic displays, rare breeds & hands-on experiences. ",  photo: "Philadelphia Zoo", latitude: "39.974701", longitude: "-75.198195"),
    placesStruct(name: "National Constitution Center", textAbout: "  The National Constitution Center is the first and only nonprofit, nonpartisan institution devoted to the U.S. Constitution and its legacy of freedom. Located two blocks from Independence Hall and the Liberty Bell in Historic Philadelphia, the Center illuminates constitutional ideals and inspires active citizenship as a state-of-the-art museum, a civic education hub and America's Town Hall.",  photo: "National Constitution Center", latitude: "39.954015", longitude: "-75.149473"),
    placesStruct(name: "National Museum of American Jewish History", textAbout: "Join us this summer at the National Museum of American Jewish History with FREE admission for the month of July, right on Independence Mall. Explore our collection of interactive exhibitions highlighting the journey of American immigrants and their stories that have helped shape America into the country we know and love. Reserve your tickets now before time runs out!",  photo: "National Museum of American Jewish History", latitude: "39.950172", longitude: "-75.148785"),
    placesStruct(name: "Independence National Historical Park", textAbout: "Independence National Historical Park is a United States National Park in Philadelphia that preserves several sites associated with the American Revolution and the nation's founding history. Administered by the National Park Service, the 55-acre (22 ha) park comprises much of Philadelphia's most-visited historic district. The park has been nicknamed 'America's most historic square mile' because of its abundance of historic landmarks, and the park sites are located within the Old City and Society Hill neighborhoods of Philadelphia.The centerpiece of the park is Independence Hall, a UNESCO World Heritage Site, where the Declaration of Independence and the United States Constitution were debated and adopted in the late 18th century.",  photo: "Independence National Historical Park", latitude: "39.949967", longitude: "-75.149726"),
    placesStruct(name: "Mutter Museum", textAbout: "  This museum, located at The College of Physicians of Philadelphia, is one of the finest medical history museums in America. The Mütter Museum is a 19th century style cabinet museum displaying medical artifacts such as anatomical specimens and medical instruments. Marvel at the beauty and strangeness of the human body. NOTICE FOR 2017: There will be no elevator access to the Mütter Museum for all of January and February 2017. The College of Physicians of Philadelphia, home of The Mütter Museum and Historical Medical Library, will be installing a new elevator from January 1st, 2017. Our new elevator will drastically improve access to our collections and events and visitors will be able to enjoy regular access as of early March, 2017.",  photo: "Mutter Museum", latitude: "39.953045", longitude: "-75.176509"),
    placesStruct(name: "Philadelphia's Magic Gardens", textAbout: "  Philadelphia's Magic Gardens (PMG)is a mosaicked visionary art environment, gallery, and community arts center that preserves, interprets and provides access to Isaiah Zagar's unique mosaic art environment and his public murals. The Magic Gardens site, Zagar's largest artwork, includes a fully tiled indoor space and large outdoor mosaic sculpture garden that spans half a block on Philadelphia's famous South Street. Inside, view PMG's ever changing exhibitions in two indoor galleries.    ",  photo: "Philadelphia's Magic Gardens", latitude: "39.942682", longitude: "-75.159314"),
    placesStruct(name: "Elfreth's Alley", textAbout: "  Elfreth's Alley is a historic street in Philadelphia, dating back to 1702. As of 2012, there are 32 houses on the street, which were built between 1728 and 1836. The Elfreth's Alley Museum is located at #124 and 126. The alley is a National Historic Landmark. Located in the Old City neighborhood, Elfreth's Alley is between North 2nd Street and North Front Street, in the block between Arch and Quarry Streets. Elfreth's Alley is named after Jeremiah Elfreth, an 18th-century blacksmith and property owner. Among the alley's residents were tradesmen and their families, including shipwrights, silver and pewter smiths, glassblowers, and furniture builders. In the 1770s, one-third of the households were headed by women. ",  photo: "Elfreth's Alley", latitude: "39.952743", longitude: "-75.142360"),
    placesStruct(name: "City Hall Visitor Center", textAbout: "  Located in the true center of Philadelphia, the City Hall Visitor Center allows visitors to experience one of the City’s most iconic buildings. Our knowledgeable Visitor Services Representatives offer visitor essentials including maps, brochures, souvenirs and trip itineraries. Interior and Tower Tours of this architectural treasure are available.",  photo: "city Hall Visitor Center", latitude: "39.952385", longitude: "-75.163406"),
    placesStruct(name: "Morris Arboretum", textAbout: "  The Morris Arboretum of the University of Pennsylvania (37 ha / 92 acres) is the official arboretum of the Commonwealth of Pennsylvania. It is located at 100 East Northwestern Avenue, Chestnut Hill, Philadelphia, Pennsylvania. The arboretum is open daily except major holidays; an admission fee is charged at the gate. The arboretum was formerly the estate of John T. (1847-1915) and Lydia T. Morris (1849-1932), a brother and sister who purchased and landscaped much of the arboretum's current site beginning in 1887. John Morris was interested in growing plants from around the world, including those collected in China by E. H. Wilson around 1900, and many of today's specimens date to Morris' original plantings.",  photo: "Morris Arboretum", latitude: "40.090748", longitude: "-75.222478"),
    placesStruct(name: "30th Street Station", textAbout: "  30th Street Station, officially William H. Gray III 30th Street Station, is an intermodal transit station in Philadelphia, Pennsylvania. It is Philadelphia's main railroad station, and is a major stop on Amtrak's Northeast and Keystone corridors. It doubles as a major commuter rail station; it is served by all Southeastern Pennsylvania Transportation Authority (SEPTA) Regional Rail lines, and is the western terminus for New Jersey Transit's Atlantic City Line. It is also served by several SEPTA city and suburban buses, as well as buses operated by NJ Transit and intercity operators.The station, which served more than 4 million inter-city rail passengers in 2018, is Amtrak's third-busiest, after Penn Station in Manhattan and Union Station in Washington, D.C., and the nation's tenth-busiest overall.    ",  photo: "30th Street Station", latitude: "39.956243", longitude: "-75.185294"),
    placesStruct(name: "Masonic Temple", textAbout: "  A Masonic Temple or Masonic Hall is, within Freemasonry, the room or edifice where a Masonic Lodge meets. Masonic Temple may also refer to an abstract spiritual goal and the conceptual ritualistic space of a meeting. In the early years of Freemasonry, from the 17th through the 18th centuries, it was most common for Masonic Lodges to form their Masonic Temples either in private homes or in the private rooms of public taverns or halls which could be regularly rented out for Masonic purposes. This was less than ideal, however; meeting in public spaces required the transportation, set-up and dismantling of increasingly elaborate paraphernalia every time the lodge met. Lodges began to look for permanent facilities, dedicated purely to Masonic use.",  photo: "Masonic Temple", latitude: "39.953391", longitude: "-75.162766"),
    placesStruct(name: "Wanamaker Organ", textAbout: "  The Wanamaker Grand Court Organ, in Philadelphia, is the largest fully functioning pipe organ in the world. The Wanamaker Organ is located within a spacious 7-story Grand Court at Macy's Center City (formerly Wanamaker's department store) and played twice a day Monday through Saturday. The organ is featured at several special concerts held throughout the year, including events featuring the Friends of the Wanamaker Organ Festival Chorus and Brass Ensemble. The Wanamaker Organ is of the American Symphonic school of design, which aims to combine traditional organ tone with the sonic colors of the symphony orchestra. In its present configuration, the Wanamaker Organ has 28,750 pipes in 464 ranks. ",  photo: "Wanamaker Organ", latitude: "39.951929", longitude: "-75.161853"),
    placesStruct(name: "University of Pennsylvania", textAbout: "  The University of Pennsylvania (Penn or UPenn) is a private Ivy League research university in Philadelphia, Pennsylvania. It is one of the nine colonial colleges founded prior to the Declaration of Independence and the first institution of higher learning in the United States to refer to itself as a university. Benjamin Franklin, Penn's founder and first president, advocated an educational program that trained leaders in commerce, government, and public service, similar to a modern liberal arts curriculum.The University of Pennsylvania is home to many professional and graduate schools, including the first school of medicine in North America (Perelman School of Medicine, 1765), the first collegiate business school (Wharton School, 1881) and the first 'student union' building and organization ",  photo: "University of Pennsylvania", latitude: "39.952172", longitude: "-75.193000"),
    placesStruct(name: "Wissahickon Valley Park", textAbout: "  Wissahickon Valley Park contains 2,042 acres (8.26 km2) of parkland in Northwest Philadelphia, including the Wissahickon Creek from its confluence with the Schuylkill River to the northwestern boundary of the city with eastern Montgomery County. Visitors travel by foot, bicycle and horse along Forbidden Drive where motor vehicles are not allowed. Side trails off Forbidden Drive lead up into the wooded gorge above the creek along a total of 50 mi (80 km) of trails. Philadelphia Parks & Recreation manages the park as the second largest part of the city's parkland areas, after the slightly larger Fairmount Park. The Wissahickon Valley was designated a National Natural Landmark in 1964, including 1,250 acres (5.1 km2) of the parkland",  photo: "Wissahickon Valley Park", latitude: "40.055611", longitude: "-75.217406"),
    placesStruct(name: "Penn Museum", textAbout: "  Open to all, the Penn Museum is home to remarkable objects and powerful stories that emerge from its extraordinary expeditions across the world. Discover captivating stories of humankind, from the very first cities of the Middle East to the kings of ancient Egypt; from the vibrant cultures of the Mediterranean to the lives of Native American communities today. Experience the mystery of the ancient past, gain an understanding of our shared humanity, and find your own place in the arc of human history.",  photo: "Penn Museum", latitude: "39.949646", longitude: "-75.190925"),
    placesStruct(name: "Cathedral Basilica of Saints Peter and Paul", textAbout: "  The Cathedral Basilica of Saints Peter and Paul, head church of the Roman Catholic Archdiocese of Philadelphia, is located at 18th Street and the Benjamin Franklin Parkway, on the east side of Logan Square in Philadelphia. It was built between 1846 and 1864, and was designed by Napoleon LeBrun, from original plans by the Reverend Mariano Muller and the Reverend John B. Tornatore, with the dome and Palladian facade, designed by John Notman, added after 1850. The interior was largely decorated by Constantino Brumidi.The cathedral is the largest Catholic church in Pennsylvania, and was listed on the U.S. National Register of Historic Places in 1971. ", photo: "Cathedral Basilica of Saints Peter and Paul", latitude: "39.957419", longitude: "-75.168831"),
    placesStruct(name: "Independence Visitor Center", textAbout: "  The Independence Visitor Center is the official visitor center of Greater Philadelphia, primary point of orientation for Independence National Historical Park, and exclusive location to pick up free, timed tickets to tour Independence Hall. Our multilingual staff are fluent in twelve languages to help all visitors. Tickets for 100+ local tours, attractions, museums, are available for purchase. Free services and amenities offered here include: official Welcome Film of Philadelphia; maps and brochures; WiFi access; and public restrooms.",  photo: "Independence Visitor Center", latitude: "39.951363", longitude: "-75.150144"),
    placesStruct(name: "Rittenhouse Square", textAbout: "  Rittenhouse Square is the name of both a public park and the surrounding neighborhood that is referred to also as Rittenhouse in Center City, Philadelphia, Pennsylvania, United States. The park is one of the five original open-space parks planned by William Penn and his surveyor Thomas Holme during the late 17th century.The neighborhood is among the highest-income urban neighborhoods in the country. Together with Fitler Square, the Rittenhouse neighborhood and the square comprise the Rittenhouse Fitler Historic District.Rittenhouse Square Park is maintained by the non-profit group, The Friends of Rittenhouse Square. Known as 'he Square,' the park is widely considered one of the finest urban public spaces in the United States. ",  photo: "Rittenhouse Square", latitude: "39.949607", longitude: "-75.171645"),
    placesStruct(name: "Fairmount Park", textAbout: "  Fairmount Park is the largest municipal park in Philadelphia, Pennsylvania and the historic name for a group of parks located throughout the city. Fairmount Park consists of two park sections named East Park and West Park, divided by the Schuylkill River, with the two sections together totalling 2,052 acres (830 ha). Management of Fairmount Park and the entire citywide park system is overseen by Philadelphia Parks & Recreation, a city department created in 2010 from the merger of the Fairmount Park Commission and the Department of Recreation.Many other city parks had also been historically included in the Fairmount Park system prior to 2010, including Wissahickon Valley Park in Northwest Philadelphia, Pennypack Park in Northeast Philadelphia, Cobbs Creek Park",  photo: "Fairmount Park", latitude: "39.981108", longitude: "-75.192894"),
]

let textInfoLabel = "This application was written for tourists and local residents of Philadelphia‎. These places are required to visit! You can build a tourist route to the main attractions using the second screen. On the third screen you can offer an interesting place! Fill out the form and send it to us. If we like it too, then all users will see this place. You can also add your places in your application on the fourth screen. It will immediately appear on the map in your app."


struct myPlacesStruct {
    var text: String
    var longitude: String
    var latitude: String
    
    init(text: String, longitude: String, latitude: String) {
        self.text = text
        self.longitude = longitude
        self.latitude = latitude
    }
}
